"""add series table and movie.series_id

Revision ID: 41853dd4ea66
Revises:
Create Date: 2025-12-17 20:16:10.558983

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41853dd4ea66"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_movies_series_id_series"), "series", ["series_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_movies_series_id_series"), type_="foreignkey"
        )

    # ### end Alembic commands ###
